title: '2. Settings'
data:
  enable_messages:
    - blog-card
    - projects-card
  blog_message_text: 'You''ve reached the end ðŸ¤¯'
  projects_message_text: 'More coming soon ðŸ¤ž'
  toggle_items:
    - Home
    - Projects
    - Blog
    - Contact
